# Generated by Django 5.1.6 on 2025-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_car_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
