# Generated by Django 5.1.6 on 2025-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
