# Generated by Django 5.1.6 on 2025-02-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_engine_capacity_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='audio',
            field=models.FileField(default=1, upload_to='media/detail_audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='media/detail_image'),
            preserve_default=False,
        ),
    ]
