# Generated by Django 5.1.6 on 2025-02-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_audio_car_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='video',
        ),
    ]
